sonar.projectKey=ssemh_cok-amacl-ogrenci-rehberlik-sistemi
sonar.sources=.
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.coverage.reportPaths=coverage/coverage-final.json
sonar.login=YOUR_TOKEN
sonar.host.url=https://sonarcloud.io 