sonar.projectKey=ssemh_cok-amacl-ogrenci-rehberlik-sistemi
sonar.sources=.
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.coverage.reportPaths=coverage/coverage-final.json
sonar.login=48f5a09d79af7f38d61382ca4eac5f152b3430bf
sonar.host.url=https://sonarcloud.io 
